# ============================ #
# == FOOD-CATALOGUE-SERVICE == #
# ============================ #

server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_catalogue
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: FOOD-CATALOGUE-SERVICE

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
